/* Data type definitions for the Large Data example 
   copied from nei-rti video streaming project
*/

module LargeData {
    // limits on element sizes
    const unsigned long  MAX_SEQUENCE_LEN = 18800000;       // 18.8MB == 100K MPEG-TS 188-byte packets
    const unsigned long LEN_PUB_ID = 8;

  typedef octet PubId[LEN_PUB_ID];
    // this is the bulk datatype for sending Large (e.g., streaming video/audio) data
    struct ccBulk {
        @key
        PubId pub_id;              // ID string of the publisher
        sequence<octet, MAX_SEQUENCE_LEN> data;     // payload of data
    };
};
