/* Data Type definitions for a large data example  */
module LargeData {
module Constants {
    /* 18.8MB  */
    const uint32 MAX_SEQUENCE_LEN = 18800000;

    const uint32 LEN_PUB_ID = 8;

    /*  QOS  */
    const string LARGE_DATA_QOS_LIBRARY = "\"LargeDataLibary\"";

    const string BEST_EFFORT_QOS_PROFILE = "\"BestEffortQosProfile\"";

  };

  typedef octet PubId[LargeData::LEN_PUB_ID];

  /*  To use a variable-sized type, the type should be annotated with @language_binding(FLAT_DATA) and 
		@mutable in combination with @transfer_mode(SHMEM_REF).  */
  @extensibility(MUTABLE)
  @transfer_mode(SHMEM_REF)
  @language_binding(FLAT_DATA)
  struct ccBulk {
    @key
    LargeData::PubId pub_id;
    sequence<octet, LargeData::MAX_SEQUENCE_LEN> data;
  };

};
